export interface Values {
  cpf:string,
  nome:string,
  dataNascimento:string,
  rua:string,
  cidade:string,
  bairro:string,
  telefone:string,
  numero:string,
  instituicao:string,
  senioridade:string,
  descricaoDoCurso:string,
  dataInicioDoCurso:string,
  dataFinalDoCurso:string,                    
  nomeEmpresa:string,
  cargo:string,
  descricaoCargo:string,
  dataInicioExperiencia:string,
  trabalhandoAtualmente:false
  dataFinalExperiencia:string
  }